[2025-02-23T14:00:03.218+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T14:00:03.261+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: newyork_weather_pipeline.transform_weather_data scheduled__2025-02-23T13:00:00+00:00 [queued]>
[2025-02-23T14:00:03.277+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: newyork_weather_pipeline.transform_weather_data scheduled__2025-02-23T13:00:00+00:00 [queued]>
[2025-02-23T14:00:03.278+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-23T14:00:03.301+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): transform_weather_data> on 2025-02-23 13:00:00+00:00
[2025-02-23T14:00:03.310+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=19459) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-23T14:00:03.312+0000] {standard_task_runner.py:72} INFO - Started process 19460 to run task
[2025-02-23T14:00:03.311+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'newyork_weather_pipeline', 'transform_weather_data', 'scheduled__2025-02-23T13:00:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/newyork_weather_pipeline/newyork_weather_etl.py', '--cfg-path', '/tmp/tmpo4e7e6sx']
[2025-02-23T14:00:03.313+0000] {standard_task_runner.py:105} INFO - Job 119: Subtask transform_weather_data
[2025-02-23T14:00:03.391+0000] {task_command.py:467} INFO - Running <TaskInstance: newyork_weather_pipeline.transform_weather_data scheduled__2025-02-23T13:00:00+00:00 [running]> on host ee2081ae3a04
[2025-02-23T14:00:03.569+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='newyork_weather_pipeline' AIRFLOW_CTX_TASK_ID='transform_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-23T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-23T13:00:00+00:00'
[2025-02-23T14:00:03.571+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T14:00:03.575+0000] {python.py:240} INFO - Done. Returned value was: {'latitude': '40.7128', 'longitude': '74.0060', 'temperature': -10.1, 'windspeed': 9.3, 'winddirection': 74, 'weathercode': 1}
[2025-02-23T14:00:03.619+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T14:00:03.619+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=newyork_weather_pipeline, task_id=transform_weather_data, run_id=scheduled__2025-02-23T13:00:00+00:00, execution_date=20250223T130000, start_date=20250223T140003, end_date=20250223T140003
[2025-02-23T14:00:03.687+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T14:00:03.721+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-23T14:00:03.724+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
