[2025-02-23T12:41:26.224+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T12:41:26.256+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: newyork_weather_pipeline.transform_weather_data scheduled__2025-02-23T11:00:00+00:00 [queued]>
[2025-02-23T12:41:26.267+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: newyork_weather_pipeline.transform_weather_data scheduled__2025-02-23T11:00:00+00:00 [queued]>
[2025-02-23T12:41:26.267+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-23T12:41:26.284+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): transform_weather_data> on 2025-02-23 11:00:00+00:00
[2025-02-23T12:41:26.290+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=18424) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-23T12:41:26.291+0000] {standard_task_runner.py:72} INFO - Started process 18425 to run task
[2025-02-23T12:41:26.292+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'newyork_weather_pipeline', 'transform_weather_data', 'scheduled__2025-02-23T11:00:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/newyork_weather_pipeline/newyork_weather_etl.py', '--cfg-path', '/tmp/tmprxvxtc9e']
[2025-02-23T12:41:26.293+0000] {standard_task_runner.py:105} INFO - Job 106: Subtask transform_weather_data
[2025-02-23T12:41:26.373+0000] {task_command.py:467} INFO - Running <TaskInstance: newyork_weather_pipeline.transform_weather_data scheduled__2025-02-23T11:00:00+00:00 [running]> on host ee2081ae3a04
[2025-02-23T12:41:26.517+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='newyork_weather_pipeline' AIRFLOW_CTX_TASK_ID='transform_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-23T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-23T11:00:00+00:00'
[2025-02-23T12:41:26.518+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T12:41:26.520+0000] {python.py:240} INFO - Done. Returned value was: {'latitude': '40.7128', 'longitude': '74.0060', 'temperature': -8.9, 'windspeed': 9.4, 'winddirection': 72, 'weathercode': 2}
[2025-02-23T12:41:26.561+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T12:41:26.561+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=newyork_weather_pipeline, task_id=transform_weather_data, run_id=scheduled__2025-02-23T11:00:00+00:00, execution_date=20250223T110000, start_date=20250223T124126, end_date=20250223T124126
[2025-02-23T12:41:26.626+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T12:41:26.659+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-23T12:41:26.662+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
